### ISSUE TITLE
[Bug]: Test fails with Jest encountered an unexpected token

### ISSUE THREAD

**Issue by amochkin** [xorde-labs/react-native-slider-verify#1]
To reproduce run `yarn test`

```text
Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    ~/repo/xorde-labs/react-native-slider-verify/node_modules/react-native/index.js:14
    import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import React from 'react';
    > 2 | import 'react-native';
        | ^
      3 | /* Note: test renderer must be required after react-native */
      4 | import * as renderer from 'react-test-renderer';
      5 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1678:14)
      at Object.<anonymous> (tests/SliderVerify.test.tsx:2:1)
```

**Comment by xtovski** [comment]
Done in f684e60647d4271a6ed67e0a93070aea8c86c072
